# Generated by Django 5.0.1 on 2024-01-15 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sendinglists',
            name='mail',
        ),
        migrations.AddField(
            model_name='mails',
            name='send_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.sendinglists', verbose_name='рассылка'),
        ),
    ]
