# Generated by Django 5.0.1 on 2024-01-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_sendinglists_mail_mails_send_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendinglists',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активна'),
        ),
    ]
