# Generated by Django 5.0.1 on 2024-01-19 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_sendinglists_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'permissions': [('set_active', 'Возможно отключить клиента')], 'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
    ]
