# Generated by Django 5.0.1 on 2024-01-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clients_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'клиенты'},
        ),
        migrations.AlterModelOptions(
            name='sendinglists',
            options={'permissions': [('set_active_sending_list', 'Возможно отключить рассылку')], 'verbose_name': 'список рассылки', 'verbose_name_plural': 'списки рассылок'},
        ),
    ]
